// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGJv7TB4ENpIyUztaWyUtYauDQTCGw698',
    appId: '1:306826868375:android:cae845b03be7ed278a5bd2',
    messagingSenderId: '306826868375',
    projectId: 'asterfox',
    storageBucket: 'asterfox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-NwJxZObo4usjhcdPHtpATqIw7WCBWiI',
    appId: '1:306826868375:ios:f940baa2b42c83588a5bd2',
    messagingSenderId: '306826868375',
    projectId: 'asterfox',
    storageBucket: 'asterfox.appspot.com',
    androidClientId: '306826868375-70i4g7bbr2jr9lc66mik2rt13laql4il.apps.googleusercontent.com',
    iosClientId: '306826868375-dsgrqo62t3915uj713ntn9eom46bhjtf.apps.googleusercontent.com',
    iosBundleId: 'net.asterfox.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbUaDEeX27IkqT4VlwVb5UfQb7cjJPWBE',
    appId: '1:306826868375:web:300c28fc8fba5c278a5bd2',
    messagingSenderId: '306826868375',
    projectId: 'asterfox',
    authDomain: 'asterfox.firebaseapp.com',
    storageBucket: 'asterfox.appspot.com',
    measurementId: 'G-7JRPLL6R76',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-NwJxZObo4usjhcdPHtpATqIw7WCBWiI',
    appId: '1:306826868375:ios:f940baa2b42c83588a5bd2',
    messagingSenderId: '306826868375',
    projectId: 'asterfox',
    storageBucket: 'asterfox.appspot.com',
    androidClientId: '306826868375-70i4g7bbr2jr9lc66mik2rt13laql4il.apps.googleusercontent.com',
    iosClientId: '306826868375-dsgrqo62t3915uj713ntn9eom46bhjtf.apps.googleusercontent.com',
    iosBundleId: 'net.asterfox.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbUaDEeX27IkqT4VlwVb5UfQb7cjJPWBE',
    appId: '1:306826868375:web:0c3dcf57a53f5fb58a5bd2',
    messagingSenderId: '306826868375',
    projectId: 'asterfox',
    authDomain: 'asterfox.firebaseapp.com',
    storageBucket: 'asterfox.appspot.com',
    measurementId: 'G-9YR9H8ZDKR',
  );

}