// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF5Ik-ea5hhvEgrBgLuHuSKlOwbNnlq_U',
    appId: '1:320722190134:android:40f5a0d141831204263d97',
    messagingSenderId: '320722190134',
    projectId: 'asterfox-88710',
    storageBucket: 'asterfox-88710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Ak19OZsnrGOINhbqruI7SIgV67SVWYc',
    appId: '1:320722190134:ios:2f5de72a9d0d4af9263d97',
    messagingSenderId: '320722190134',
    projectId: 'asterfox-88710',
    storageBucket: 'asterfox-88710.appspot.com',
    iosClientId: '320722190134-mv9p0itd6tsofnm63v82litegj18i2sj.apps.googleusercontent.com',
    iosBundleId: 'net.asterfox.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Ak19OZsnrGOINhbqruI7SIgV67SVWYc',
    appId: '1:320722190134:ios:2f5de72a9d0d4af9263d97',
    messagingSenderId: '320722190134',
    projectId: 'asterfox-88710',
    storageBucket: 'asterfox-88710.appspot.com',
    iosClientId: '320722190134-mv9p0itd6tsofnm63v82litegj18i2sj.apps.googleusercontent.com',
    iosBundleId: 'net.asterfox.app',
  );
}
