name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Generate build files
    strategy:
      fail-fast: false
      matrix:
        target: [windows, linux, macos]
        arch: [x64, arm64]
        include:
          - target: android
            runner: ubuntu-latest
            build: flutter build apk
            artifact: ./build/app/outputs/flutter-apk/app-release.apk
          - target: windows
            runner: windows-latest
            build: dart run msix:create --install-certificate false
            artifact: ./build/windows/{0}/runner/Release
          - target: linux
            runner: ubuntu-latest
            build: sudo $(which flutter) build linux
            artifact: ./build/linux/{0}/release/bundle
          # - target: macos
          #   runner: macos-latest
          #   build: flutter build macos
          #   artifact: build/macos/Build/Products/Release
        exclude:
          - target: windows
            arch: arm64
          - target: linux
            arch: arm64
          - target: macos
            # arch: x64
    runs-on: ${{ matrix.runner }}
    env:
      branch: ${{ github.ref }}
      commitId: ${{ github.sha }}
      artifactSuffix: ${{ matrix.arch && format('-{0}', matrix.arch) || '' }}
      artifact: ${{ format(matrix.artifact, matrix.arch) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - if: matrix.target == 'android'
        name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      
      - if: matrix.target == 'linux'
        name: Install native dependencies
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev libwebkit2gtk-4.0-dev libmpv-dev mpv

      - name: Initialize flutter
        uses: subosito/flutter-action@v2

      - name: Generate l10n files
        run: flutter gen-l10n
      
      - name: Generate git info
        shell: bash
        run: |
          git init
          echo "ref: ${{ env.branch }}" > .git/HEAD
          echo "${{ env.commitId }}" > .git/${{ env.branch }}

      - name: Decode certificate
        if: matrix.target == 'windows'
        shell: bash
        run: |
          echo ${{ secrets.PFX_BASE64 }} | base64 -d > ./certificate.pfx

      - name: Build release
        run: ${{ matrix.build }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: asterfox-${{ matrix.target }}${{ env.artifactSuffix }}
          path: ${{ env.artifact }}
    
    
