name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Generate build files
    strategy: 
      matrix:
        target: [android, windows, linux]
        include:
          - target: android
            runner: ubuntu-latest
            build: flutter build apk
            artifact: ./build/app/outputs/flutter-apk/app-release.apk
            artifactSuffix: ""
          - target: windows
            runner: windows-latest
            build: dart run msix:create --install-certificate false
            artifact: ./build/windows/x64/runner/Release
            artifactSuffix: "-x64"
          - target: linux
            runner: ubuntu-latest
            build: sudo $(which flutter) build linux --release
            artifact: ./build/linux/x64/release/bundle
            artifactSuffix: "-x64"
        
    runs-on: ${{ matrix.runner }}
    env:
      branch: ${{ github.ref }}
      commitId: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - if: matrix.target == 'android'
        name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      
      - if: matrix.target == 'linux'
        name: Install native dependencies
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Initialize flutter
        uses: subosito/flutter-action@v2

      - name: Generate l10n files
        run: flutter gen-l10n
      
      - name: Generate git info
        shell: bash
        run: |
          git init
          echo "ref: ${{ env.branch }}" > .git/HEAD
          echo "${{ env.commitId }}" > .git/${{ env.branch }}

      - name: Decode certificate
        if: matrix.target == 'windows'
        shell: bash
        run: |
          echo ${{ secrets.PFX_BASE64 }} | base64 -d > ./certificate.pfx

      - name: Build release
        run: ${{ matrix.build}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: asterfox-${{ matrix.target }}${{ matrix.artifactSuffix}}
          path: ${{ matrix.artifact }}
    
    
