name: Build for Linux (arm64)
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Generate build for Linux (arm64)
    runs-on: ubuntu-latest
    env:
      branch: ${{ github.ref }}
      commitId: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate git info
        shell: bash
        run: |
          git init
          echo "ref: ${{ env.branch }}" > .git/HEAD
          echo "${{ env.commitId }}" > .git/${{ env.branch }}

      - name: Run on arm64 architecture
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          setup: |
            mkdir -p "${PWD}/build"
          dockerRunArgs: |
            --volume "${PWD}/build:/build"
          install: |
            apt update -y
            DEBIAN_FRONTEND=noninteractive apt install -y tzdata
            apt install -y ninja-build libgtk-3-dev libwebkit2gtk-4.0-dev

            apt install -y git curl unzip cmake clang

            git clone https://github.com/flutter/flutter.git
            cd flutter
            git checkout stable
            cd ..

            flutter="/flutter/bin/flutter"
            echo "Flutter installed successfully at $flutter"

            $flutter doctor -v
            $flutter config --enable-linux-desktop

          run: |
            flutter="/flutter/bin/flutter"
            $flutter gen-l10n
            $flutter build linux --release

            echo "Build successful for Linux (arm64)"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: asterfox-linux-arm64
          path: ./build/linux/arm64/release/bundle
    
    
