name: Build msix
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Generate msix
    runs-on: ubuntu-latest
    env:
      branch: ${{ github.ref }}
      commitId: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize flutter
        uses: subosito/flutter-action@v2

      - name: Generate l10n files
        run: flutter gen-l10n
      
      - name: Generate git info
        shell: bash
        run: |
          git init
          echo "ref: ${{ env.branch }}" > .git/HEAD
          echo "${{ env.commitId }}" > .git/${{ env.branch }}

      - name: Build release msix
        run: dart run msix:create

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: asterfox
          path: ./build/windows/x64/runner/Release/asterfox.msix